pipeline {
    agent any

    triggers {
        githubPush()
    }

    environment {
        PATH = "/Users/user/.docker/bin:/usr/local/bin:/usr/bin:/bin:${env.PATH}"

        IMAGE_NAME = 'distributed-web-app'

        NEXUS_PYPI_URL = 'http://localhost:8081/repository/pypi-group/simple/'
    }

    stages {

        stage('Environment') {
            steps {
                sh '''
                    echo "===== ENVIRONMENT ====="
                    python3 --version
                    docker --version
                    git --version
                    pwd
                    ls -la
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('web-app') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'nexus-pypi',
                            usernameVariable: 'NEXUS_USER',
                            passwordVariable: 'NEXUS_PASSWORD'
                        )
                    ]) {
                        sh '''
                            set -e

                            echo "===== CREATE VIRTUAL ENVIRONMENT ====="

                            rm -rf .venv
                            python3 -m venv .venv

                            .venv/bin/python -m pip install --upgrade pip

                            echo "===== INSTALL REQUIREMENTS FROM NEXUS ====="

                            .venv/bin/pip install \
                                --index-url "http://${NEXUS_USER}:${NEXUS_PASSWORD}@localhost:8081/repository/pypi-group/simple/" \
                                -r requirements.txt


                            echo "===== INSTALLED PACKAGES ====="

                            .venv/bin/pip list
                        '''
                    }
                }
            }
        }

        stage('Test') {
            steps {
                dir('web-app') {
                    sh '''
                        set -e

                        echo "===== TEST APPLICATION IMPORT ====="

                        .venv/bin/python -c "
from app import app
import my_processor

print('Application import successful')
print('my_processor import successful')
print('my_processor location:', my_processor.__file__)
"

                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('web-app') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'nexus-pypi',
                            usernameVariable: 'NEXUS_USER',
                            passwordVariable: 'NEXUS_PASSWORD'
                        )
                    ]) {
                        sh '''
                            docker build \
                                --build-arg NEXUS_URL="http://${NEXUS_USER}:${NEXUS_PASSWORD}@host.docker.internal:8081/repository/pypi-group/simple/" \
                                -t ${IMAGE_NAME}:${BUILD_NUMBER} \
                                -t ${IMAGE_NAME}:latest \
                                .
                        '''
                    }
                }
            }
        }

        stage('Docker Images') {
            steps {
                sh '''
                    echo "===== DOCKER IMAGES ====="

                    docker images ${IMAGE_NAME}
                '''
            }
        }
    }

    post {
        success {
            echo 'Web application Docker image built successfully.'
        }

        failure {
            echo 'Web application pipeline failed.'
        }
    }
}